### PR TITLE
Login bug

### LINKED ISSUE #119: Login page not showing in sugar factory if user is not loggedin

### PR DESCRIPTION
**Pull request by LovedeepSingh19**

### CODE REVIEW

File: apps/factory/src/pages/[username]/[packageName]/[template]/index.tsx [hunk 1]
```diff
@@ -9,6 +9,17 @@ const TemplateWithoutVersion = () => {
...
 
+  //// Hack for fixing of redirection to sugarcubes instead of api/auth/signin from homepage button
+  //
+
+  if (username === "api" && packageName === "auth" && template === "signin") {
+    useEffect(() => {
+      window.location.reload();
+    }, []);
+  }
+
```
Comment (LovedeepSingh19) [inline apps/factory/src/pages/[username]/[packageName]/[template]/index.tsx:20]: Reloading the page if the route is /api/auth/signin
